---
title: "Final Project: First Stage"
author: Miriam Schäfer, Daniel Rohrbach
format: html
editor: visual
echo: false
message: false
warning: false
---

```{r}
here::i_am("final-project-sdg8.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
library(stringr)
```

[Link to the Github](https://github.com/dauphine-data-daniel/final-project-sdg8)

## Data sources

The International Labour Organization (ILO) datasets serve as the cornerstone of our analysis on the Global Progress Towards Sustainable Development Goal (SDG) 8, which emphasizes 'Decent Work and Economic Growth'. \n

The ILO, a specialized agency of the United Nations, has a comprehensive set of data sets that are of great importance for understanding the various facets of the labor market, employment trends and economic growth on a global level. These datasets are carefully collected, regularly updated, and represent a reliable and comprehensive source of information.\n

SDG 8 aims to promote sustained, inclusive, and sustainable economic growth, full and productive employment, and decent work for all. In order to effectively analyze progress towards this goal, access to detailed and accurate labor statistics is essential. \n

The [ILOSTAT](https://test-ilostat.pantheonsite.io/data/#) data sets are particularly suitable for this purpose as they provide comprehensive data on aspects such as employment rates, wage differentials, labor productivity and working conditions. This broad range of data enables a thorough examination of the global labor market and economic activities.\n

The ILO's commitment to providing a wide range of data is reflected in its collection of datasets. These provide the necessary tools to assess progress and challenges in achieving SDG 8, enabling a nuanced understanding of how different regions, genders, and economic sectors are performing in the context of decent work and economic growth.\n

Another critical aspect of our analysis is understanding the influence of democratic values on economic growth and labor markets. For this purpose, we turn to [The Economist's World Democracy Index](https://ourworldindata.org/grapher/democracy-index-eiu). This index is a unique tool that measures the state of democracy in 167 countries, scoring each on a scale of 0 to 10 based on five categories: electoral process and pluralism, civil liberties, the functioning of government, political participation, and political culture.\n

By examining the correlations between a country's score on the Democracy Index and its performance in terms of SDG 8, we aim to uncover potential relationships between democratic governance and the quality of economic growth and employment.\n

The integration of data from the ILO datasets and The Economist's World Democracy Index offers a holistic view of the progress towards SDG 8. The ILO's labor market and economic data provide a quantitative foundation, while the Democracy Index adds a qualitative dimension, allowing us to explore how political and social factors might influence economic and labor market outcomes. This combination of sources ensures a well-rounded analysis, encompassing a range of variables that can impact the achievement of decent work and economic growth globally.\n

In summary, the ILO datasets are invaluable in providing the necessary data for a comprehensive analysis of global progress towards SDG 8. They offer detailed insights into labor market trends, wage dynamics, and employment conditions across different regions and demographics. Complementing this with data from The Economist's World Democracy Index allows us to explore the broader socio-political context in which economic activities and labor markets operate. Together, these sources form the backbone of our analysis, enabling a robust and multifaceted exploration of the global journey towards achieving decent work and economic growth.\n


## Research Question

At the heart of our research project is a central question: how far has the world progressed towards achieving Sustainable Development Goal 8 (SDG 8) - promoting economic growth with decent work - and what milestones have been reached or what challenges need to be overcome as the 2030 deadline approaches? This comprehensive analysis uses extensive data sets to shed light on the different facets of this question and provide a nuanced understanding of global progress and setbacks in this important area.\n

SDG 8, a key component of the United Nations Sustainable Development Goals, focuses on promoting sustained, inclusive, and sustainable economic growth, full and productive employment and decent work for all. This goal is not only an economic goal, but also encompasses broader aspects of social and environmental development, making it a complex and multidimensional goal. Our research aims to analyze these dimensions by examining various indicators such as unemployment rates, gender equality in the labor market, labor safety standards and regional inequalities, in the context of different democratic regimes and values.\n

A significant part of our analysis is dedicated to understanding global unemployment trends. Unemployment rates are a direct indicator of economic vitality and the health of the labor market. Using these rates, we can assess the effectiveness of policies and initiatives to promote employment and therefore economic growth.\n

Gender equality in the world of work is another important aspect of our research. We want to investigate what progress has been made in closing the gender gap in employment and equal pay. This research will provide insights into the equitable distribution of economic opportunities, highlighting broader societal trends in gender roles and equality.\n

Workplace safety is a fundamental component of decent working conditions. As part of our research, we will examine global trends in occupational safety, including the incidence of workplace accidents and the effectiveness of safety regulations and practices. This aspect of the research is crucial to understanding how far we have come in ensuring a safe working environment for all workers.\n

The research will also consider regional inequalities in the achievement of SDG 8. Economic development and working conditions vary widely across regions and are influenced by factors such as political stability, quality of governance and economic policies. By analyzing these regional differences, we can identify patterns and unique challenges faced by different parts of the world. In addition, we will focus on the influence of democratic values on economic and working conditions, examining how governance styles affect the implementation and success of policies to achieve SDG 8.\n

As we approach the 2030 deadline for the SDGs, it is crucial to measure the progress made so far. Our research aims to identify the milestones already achieved in the realization of SDG 8. The aim is not only to highlight the successes, but also to identify the critical areas where additional efforts are needed. The aim is to paint a clear picture of the current state of play and provide insights into effective strategies and actions that could accelerate progress towards the 2030 goals.\n

In summary, our research question forms the basis for a comprehensive analysis aimed at understanding global progress towards SDG 8. By examining various indicators and factors, from unemployment and gender equality to occupational safety and regional differences, all in the context of democratic values, we aim to provide a comprehensive overview of where the world stands on its path to sustainable economic growth and decent work by 2030.\n
